### PR TITLE
Changed return value type of get_function member

### PR DESCRIPTION
**Pull request by martin-olivier**
# Description

Return value of `get_function` is now a function pointer instead of an `std::function`

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [X] I have added sufficient documentation in the code

### CODE REVIEW

**Comment by eyalroz** [comment]
Interesting that you didn't have to change any test code...

However - your test suite fails for me both on the main branch and on this branch.

**Comment by martin-olivier** [comment]
I currently don't have to change unit tests code because i used `auto` to get the return value of `get_function` and the syntax still the same for `get_function` template and the function call itself

**Comment by eyalroz** [comment]
So, you're returning a reference to a pointer... why not just return the pointer itself?

**Comment by martin-olivier** [comment]
I'm dereferencing it so it ends up with a function reference not a reference on function pointer am i right ?
```c++
// with T = double(double, double) for example
return *reinterpret_cast<T *>(sym);
```
I was thinking of doing that so `get_function` return type is similar with `get_variable` :
```c++
// return T& with T = double(double, double)
auto &fn = lib.get_function<double(double, double)>("adder");

// return T& with T = double
double &var = lib.get_variable<double>("pi");
```

**Comment by eyalroz** [comment]
> am I right?

Not really, because "functions" in C (and C++, sort of) _are_ pointers. Please read:

**Comment by martin-olivier** [comment]
> Not really, because "functions" in C (and C++, sort of) are pointers. Please read: [This SO answer](https://stackoverflow.com/a/45659572/1593077).

Thanks for sharing this info.
I have just applied your request changes on https://github.com/martin-olivier/dylib/pull/28

Fell free to review

**Pull request merged**
